<?php 
session_start();
unset($_SESSION['id']);
unset($_SESSION['email']);
unset($_SESSION['firstname']);
unset($_SESSION['lastname']);
unset($_SESSION['phone']);
unset($_SESSION['username']);
unset($_SESSION['admin']);
unset($_SESSION['priority']);
session_destroy();
header('location:../home.php');exit;
?>